// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fila/v1/admin.proto

package filav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *QueueConfig           `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueRequest) GetConfig() *QueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueueConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OnEnqueueScript     string                 `protobuf:"bytes,1,opt,name=on_enqueue_script,json=onEnqueueScript,proto3" json:"on_enqueue_script,omitempty"`
	OnFailureScript     string                 `protobuf:"bytes,2,opt,name=on_failure_script,json=onFailureScript,proto3" json:"on_failure_script,omitempty"`
	VisibilityTimeoutMs uint64                 `protobuf:"varint,3,opt,name=visibility_timeout_ms,json=visibilityTimeoutMs,proto3" json:"visibility_timeout_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueueConfig) Reset() {
	*x = QueueConfig{}
	mi := &file_fila_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConfig) ProtoMessage() {}

func (x *QueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConfig.ProtoReflect.Descriptor instead.
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *QueueConfig) GetOnEnqueueScript() string {
	if x != nil {
		return x.OnEnqueueScript
	}
	return ""
}

func (x *QueueConfig) GetOnFailureScript() string {
	if x != nil {
		return x.OnFailureScript
	}
	return ""
}

func (x *QueueConfig) GetVisibilityTimeoutMs() uint64 {
	if x != nil {
		return x.VisibilityTimeoutMs
	}
	return 0
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateQueueResponse) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type DeleteQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueResponse) Reset() {
	*x = DeleteQueueResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueResponse) ProtoMessage() {}

func (x *DeleteQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteQueueResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{4}
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *SetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{6}
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConfigEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigEntry) Reset() {
	*x = ConfigEntry{}
	mi := &file_fila_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigEntry) ProtoMessage() {}

func (x *ConfigEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigEntry.ProtoReflect.Descriptor instead.
func (*ConfigEntry) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigRequest) Reset() {
	*x = ListConfigRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigRequest) ProtoMessage() {}

func (x *ListConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigRequest.ProtoReflect.Descriptor instead.
func (*ListConfigRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ListConfigRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ConfigEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigResponse) Reset() {
	*x = ListConfigResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigResponse) ProtoMessage() {}

func (x *ListConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigResponse.ProtoReflect.Descriptor instead.
func (*ListConfigResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListConfigResponse) GetEntries() []*ConfigEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListConfigResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type PerFairnessKeyStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PendingCount   uint64                 `protobuf:"varint,2,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	CurrentDeficit int64                  `protobuf:"varint,3,opt,name=current_deficit,json=currentDeficit,proto3" json:"current_deficit,omitempty"`
	Weight         uint32                 `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PerFairnessKeyStats) Reset() {
	*x = PerFairnessKeyStats{}
	mi := &file_fila_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerFairnessKeyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerFairnessKeyStats) ProtoMessage() {}

func (x *PerFairnessKeyStats) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerFairnessKeyStats.ProtoReflect.Descriptor instead.
func (*PerFairnessKeyStats) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *PerFairnessKeyStats) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PerFairnessKeyStats) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *PerFairnessKeyStats) GetCurrentDeficit() int64 {
	if x != nil {
		return x.CurrentDeficit
	}
	return 0
}

func (x *PerFairnessKeyStats) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PerThrottleKeyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Tokens        float64                `protobuf:"fixed64,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	RatePerSecond float64                `protobuf:"fixed64,3,opt,name=rate_per_second,json=ratePerSecond,proto3" json:"rate_per_second,omitempty"`
	Burst         float64                `protobuf:"fixed64,4,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerThrottleKeyStats) Reset() {
	*x = PerThrottleKeyStats{}
	mi := &file_fila_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerThrottleKeyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerThrottleKeyStats) ProtoMessage() {}

func (x *PerThrottleKeyStats) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerThrottleKeyStats.ProtoReflect.Descriptor instead.
func (*PerThrottleKeyStats) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *PerThrottleKeyStats) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PerThrottleKeyStats) GetTokens() float64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *PerThrottleKeyStats) GetRatePerSecond() float64 {
	if x != nil {
		return x.RatePerSecond
	}
	return 0
}

func (x *PerThrottleKeyStats) GetBurst() float64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type GetStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Depth              uint64                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	InFlight           uint64                 `protobuf:"varint,2,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	ActiveFairnessKeys uint64                 `protobuf:"varint,3,opt,name=active_fairness_keys,json=activeFairnessKeys,proto3" json:"active_fairness_keys,omitempty"`
	ActiveConsumers    uint32                 `protobuf:"varint,4,opt,name=active_consumers,json=activeConsumers,proto3" json:"active_consumers,omitempty"`
	Quantum            uint32                 `protobuf:"varint,5,opt,name=quantum,proto3" json:"quantum,omitempty"`
	PerKeyStats        []*PerFairnessKeyStats `protobuf:"bytes,6,rep,name=per_key_stats,json=perKeyStats,proto3" json:"per_key_stats,omitempty"`
	PerThrottleStats   []*PerThrottleKeyStats `protobuf:"bytes,7,rep,name=per_throttle_stats,json=perThrottleStats,proto3" json:"per_throttle_stats,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsResponse) GetDepth() uint64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GetStatsResponse) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *GetStatsResponse) GetActiveFairnessKeys() uint64 {
	if x != nil {
		return x.ActiveFairnessKeys
	}
	return 0
}

func (x *GetStatsResponse) GetActiveConsumers() uint32 {
	if x != nil {
		return x.ActiveConsumers
	}
	return 0
}

func (x *GetStatsResponse) GetQuantum() uint32 {
	if x != nil {
		return x.Quantum
	}
	return 0
}

func (x *GetStatsResponse) GetPerKeyStats() []*PerFairnessKeyStats {
	if x != nil {
		return x.PerKeyStats
	}
	return nil
}

func (x *GetStatsResponse) GetPerThrottleStats() []*PerThrottleKeyStats {
	if x != nil {
		return x.PerThrottleStats
	}
	return nil
}

type RedriveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlqQueue      string                 `protobuf:"bytes,1,opt,name=dlq_queue,json=dlqQueue,proto3" json:"dlq_queue,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveRequest) Reset() {
	*x = RedriveRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveRequest) ProtoMessage() {}

func (x *RedriveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveRequest.ProtoReflect.Descriptor instead.
func (*RedriveRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RedriveRequest) GetDlqQueue() string {
	if x != nil {
		return x.DlqQueue
	}
	return ""
}

func (x *RedriveRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RedriveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redriven      uint64                 `protobuf:"varint,1,opt,name=redriven,proto3" json:"redriven,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveResponse) Reset() {
	*x = RedriveResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveResponse) ProtoMessage() {}

func (x *RedriveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveResponse.ProtoReflect.Descriptor instead.
func (*RedriveResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RedriveResponse) GetRedriven() uint64 {
	if x != nil {
		return x.Redriven
	}
	return 0
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_fila_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{18}
}

type QueueInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Depth           uint64                 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	InFlight        uint64                 `protobuf:"varint,3,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	ActiveConsumers uint32                 `protobuf:"varint,4,opt,name=active_consumers,json=activeConsumers,proto3" json:"active_consumers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_fila_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetDepth() uint64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *QueueInfo) GetInFlight() uint64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *QueueInfo) GetActiveConsumers() uint32 {
	if x != nil {
		return x.ActiveConsumers
	}
	return 0
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_fila_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_fila_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

var File_fila_v1_admin_proto protoreflect.FileDescriptor

const file_fila_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x13fila/v1/admin.proto\x12\afila.v1\"V\n" +
	"\x12CreateQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.fila.v1.QueueConfigR\x06config\"\x99\x01\n" +
	"\vQueueConfig\x12*\n" +
	"\x11on_enqueue_script\x18\x01 \x01(\tR\x0fonEnqueueScript\x12*\n" +
	"\x11on_failure_script\x18\x02 \x01(\tR\x0fonFailureScript\x122\n" +
	"\x15visibility_timeout_ms\x18\x03 \x01(\x04R\x13visibilityTimeoutMs\"0\n" +
	"\x13CreateQueueResponse\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"*\n" +
	"\x12DeleteQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\x15\n" +
	"\x13DeleteQueueResponse\":\n" +
	"\x10SetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x13\n" +
	"\x11SetConfigResponse\"$\n" +
	"\x10GetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11GetConfigResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"5\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"+\n" +
	"\x11ListConfigRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"e\n" +
	"\x12ListConfigResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.fila.v1.ConfigEntryR\aentries\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\"'\n" +
	"\x0fGetStatsRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\x8d\x01\n" +
	"\x13PerFairnessKeyStats\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\rpending_count\x18\x02 \x01(\x04R\fpendingCount\x12'\n" +
	"\x0fcurrent_deficit\x18\x03 \x01(\x03R\x0ecurrentDeficit\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\rR\x06weight\"}\n" +
	"\x13PerThrottleKeyStats\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x01R\x06tokens\x12&\n" +
	"\x0frate_per_second\x18\x03 \x01(\x01R\rratePerSecond\x12\x14\n" +
	"\x05burst\x18\x04 \x01(\x01R\x05burst\"\xca\x02\n" +
	"\x10GetStatsResponse\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\x04R\x05depth\x12\x1b\n" +
	"\tin_flight\x18\x02 \x01(\x04R\binFlight\x120\n" +
	"\x14active_fairness_keys\x18\x03 \x01(\x04R\x12activeFairnessKeys\x12)\n" +
	"\x10active_consumers\x18\x04 \x01(\rR\x0factiveConsumers\x12\x18\n" +
	"\aquantum\x18\x05 \x01(\rR\aquantum\x12@\n" +
	"\rper_key_stats\x18\x06 \x03(\v2\x1c.fila.v1.PerFairnessKeyStatsR\vperKeyStats\x12J\n" +
	"\x12per_throttle_stats\x18\a \x03(\v2\x1c.fila.v1.PerThrottleKeyStatsR\x10perThrottleStats\"C\n" +
	"\x0eRedriveRequest\x12\x1b\n" +
	"\tdlq_queue\x18\x01 \x01(\tR\bdlqQueue\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"-\n" +
	"\x0fRedriveResponse\x12\x1a\n" +
	"\bredriven\x18\x01 \x01(\x04R\bredriven\"\x13\n" +
	"\x11ListQueuesRequest\"}\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x04R\x05depth\x12\x1b\n" +
	"\tin_flight\x18\x03 \x01(\x04R\binFlight\x12)\n" +
	"\x10active_consumers\x18\x04 \x01(\rR\x0factiveConsumers\"@\n" +
	"\x12ListQueuesResponse\x12*\n" +
	"\x06queues\x18\x01 \x03(\v2\x12.fila.v1.QueueInfoR\x06queues2\xb4\x04\n" +
	"\tFilaAdmin\x12H\n" +
	"\vCreateQueue\x12\x1b.fila.v1.CreateQueueRequest\x1a\x1c.fila.v1.CreateQueueResponse\x12H\n" +
	"\vDeleteQueue\x12\x1b.fila.v1.DeleteQueueRequest\x1a\x1c.fila.v1.DeleteQueueResponse\x12B\n" +
	"\tSetConfig\x12\x19.fila.v1.SetConfigRequest\x1a\x1a.fila.v1.SetConfigResponse\x12B\n" +
	"\tGetConfig\x12\x19.fila.v1.GetConfigRequest\x1a\x1a.fila.v1.GetConfigResponse\x12E\n" +
	"\n" +
	"ListConfig\x12\x1a.fila.v1.ListConfigRequest\x1a\x1b.fila.v1.ListConfigResponse\x12?\n" +
	"\bGetStats\x12\x18.fila.v1.GetStatsRequest\x1a\x19.fila.v1.GetStatsResponse\x12<\n" +
	"\aRedrive\x12\x17.fila.v1.RedriveRequest\x1a\x18.fila.v1.RedriveResponse\x12E\n" +
	"\n" +
	"ListQueues\x12\x1a.fila.v1.ListQueuesRequest\x1a\x1b.fila.v1.ListQueuesResponseB\"Z github.com/faisca/fila-go/filav1b\x06proto3"

var (
	file_fila_v1_admin_proto_rawDescOnce sync.Once
	file_fila_v1_admin_proto_rawDescData []byte
)

func file_fila_v1_admin_proto_rawDescGZIP() []byte {
	file_fila_v1_admin_proto_rawDescOnce.Do(func() {
		file_fila_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fila_v1_admin_proto_rawDesc), len(file_fila_v1_admin_proto_rawDesc)))
	})
	return file_fila_v1_admin_proto_rawDescData
}

var file_fila_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_fila_v1_admin_proto_goTypes = []any{
	(*CreateQueueRequest)(nil),  // 0: fila.v1.CreateQueueRequest
	(*QueueConfig)(nil),         // 1: fila.v1.QueueConfig
	(*CreateQueueResponse)(nil), // 2: fila.v1.CreateQueueResponse
	(*DeleteQueueRequest)(nil),  // 3: fila.v1.DeleteQueueRequest
	(*DeleteQueueResponse)(nil), // 4: fila.v1.DeleteQueueResponse
	(*SetConfigRequest)(nil),    // 5: fila.v1.SetConfigRequest
	(*SetConfigResponse)(nil),   // 6: fila.v1.SetConfigResponse
	(*GetConfigRequest)(nil),    // 7: fila.v1.GetConfigRequest
	(*GetConfigResponse)(nil),   // 8: fila.v1.GetConfigResponse
	(*ConfigEntry)(nil),         // 9: fila.v1.ConfigEntry
	(*ListConfigRequest)(nil),   // 10: fila.v1.ListConfigRequest
	(*ListConfigResponse)(nil),  // 11: fila.v1.ListConfigResponse
	(*GetStatsRequest)(nil),     // 12: fila.v1.GetStatsRequest
	(*PerFairnessKeyStats)(nil), // 13: fila.v1.PerFairnessKeyStats
	(*PerThrottleKeyStats)(nil), // 14: fila.v1.PerThrottleKeyStats
	(*GetStatsResponse)(nil),    // 15: fila.v1.GetStatsResponse
	(*RedriveRequest)(nil),      // 16: fila.v1.RedriveRequest
	(*RedriveResponse)(nil),     // 17: fila.v1.RedriveResponse
	(*ListQueuesRequest)(nil),   // 18: fila.v1.ListQueuesRequest
	(*QueueInfo)(nil),           // 19: fila.v1.QueueInfo
	(*ListQueuesResponse)(nil),  // 20: fila.v1.ListQueuesResponse
}
var file_fila_v1_admin_proto_depIdxs = []int32{
	1,  // 0: fila.v1.CreateQueueRequest.config:type_name -> fila.v1.QueueConfig
	9,  // 1: fila.v1.ListConfigResponse.entries:type_name -> fila.v1.ConfigEntry
	13, // 2: fila.v1.GetStatsResponse.per_key_stats:type_name -> fila.v1.PerFairnessKeyStats
	14, // 3: fila.v1.GetStatsResponse.per_throttle_stats:type_name -> fila.v1.PerThrottleKeyStats
	19, // 4: fila.v1.ListQueuesResponse.queues:type_name -> fila.v1.QueueInfo
	0,  // 5: fila.v1.FilaAdmin.CreateQueue:input_type -> fila.v1.CreateQueueRequest
	3,  // 6: fila.v1.FilaAdmin.DeleteQueue:input_type -> fila.v1.DeleteQueueRequest
	5,  // 7: fila.v1.FilaAdmin.SetConfig:input_type -> fila.v1.SetConfigRequest
	7,  // 8: fila.v1.FilaAdmin.GetConfig:input_type -> fila.v1.GetConfigRequest
	10, // 9: fila.v1.FilaAdmin.ListConfig:input_type -> fila.v1.ListConfigRequest
	12, // 10: fila.v1.FilaAdmin.GetStats:input_type -> fila.v1.GetStatsRequest
	16, // 11: fila.v1.FilaAdmin.Redrive:input_type -> fila.v1.RedriveRequest
	18, // 12: fila.v1.FilaAdmin.ListQueues:input_type -> fila.v1.ListQueuesRequest
	2,  // 13: fila.v1.FilaAdmin.CreateQueue:output_type -> fila.v1.CreateQueueResponse
	4,  // 14: fila.v1.FilaAdmin.DeleteQueue:output_type -> fila.v1.DeleteQueueResponse
	6,  // 15: fila.v1.FilaAdmin.SetConfig:output_type -> fila.v1.SetConfigResponse
	8,  // 16: fila.v1.FilaAdmin.GetConfig:output_type -> fila.v1.GetConfigResponse
	11, // 17: fila.v1.FilaAdmin.ListConfig:output_type -> fila.v1.ListConfigResponse
	15, // 18: fila.v1.FilaAdmin.GetStats:output_type -> fila.v1.GetStatsResponse
	17, // 19: fila.v1.FilaAdmin.Redrive:output_type -> fila.v1.RedriveResponse
	20, // 20: fila.v1.FilaAdmin.ListQueues:output_type -> fila.v1.ListQueuesResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_fila_v1_admin_proto_init() }
func file_fila_v1_admin_proto_init() {
	if File_fila_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fila_v1_admin_proto_rawDesc), len(file_fila_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fila_v1_admin_proto_goTypes,
		DependencyIndexes: file_fila_v1_admin_proto_depIdxs,
		MessageInfos:      file_fila_v1_admin_proto_msgTypes,
	}.Build()
	File_fila_v1_admin_proto = out.File
	file_fila_v1_admin_proto_goTypes = nil
	file_fila_v1_admin_proto_depIdxs = nil
}
