// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fila/v1/messages.proto

package filav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Core message envelope persisted in the broker.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *MessageMetadata       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamps    *MessageTimestamps     `protobuf:"bytes,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_fila_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_fila_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetMetadata() *MessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamps() *MessageTimestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// Broker-assigned scheduling metadata.
type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FairnessKey   string                 `protobuf:"bytes,1,opt,name=fairness_key,json=fairnessKey,proto3" json:"fairness_key,omitempty"`
	Weight        uint32                 `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	ThrottleKeys  []string               `protobuf:"bytes,3,rep,name=throttle_keys,json=throttleKeys,proto3" json:"throttle_keys,omitempty"`
	AttemptCount  uint32                 `protobuf:"varint,4,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	QueueId       string                 `protobuf:"bytes,5,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_fila_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_fila_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *MessageMetadata) GetFairnessKey() string {
	if x != nil {
		return x.FairnessKey
	}
	return ""
}

func (x *MessageMetadata) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *MessageMetadata) GetThrottleKeys() []string {
	if x != nil {
		return x.ThrottleKeys
	}
	return nil
}

func (x *MessageMetadata) GetAttemptCount() uint32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *MessageMetadata) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

// Lifecycle timestamps attached to every message.
type MessageTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	LeasedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=leased_at,json=leasedAt,proto3" json:"leased_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTimestamps) Reset() {
	*x = MessageTimestamps{}
	mi := &file_fila_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTimestamps) ProtoMessage() {}

func (x *MessageTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_fila_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTimestamps.ProtoReflect.Descriptor instead.
func (*MessageTimestamps) Descriptor() ([]byte, []int) {
	return file_fila_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *MessageTimestamps) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *MessageTimestamps) GetLeasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeasedAt
	}
	return nil
}

var File_fila_v1_messages_proto protoreflect.FileDescriptor

const file_fila_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x16fila/v1/messages.proto\x12\afila.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\aheaders\x18\x02 \x03(\v2\x1d.fila.v1.Message.HeadersEntryR\aheaders\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x124\n" +
	"\bmetadata\x18\x04 \x01(\v2\x18.fila.v1.MessageMetadataR\bmetadata\x12:\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\v2\x1a.fila.v1.MessageTimestampsR\n" +
	"timestamps\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x0fMessageMetadata\x12!\n" +
	"\ffairness_key\x18\x01 \x01(\tR\vfairnessKey\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\rR\x06weight\x12#\n" +
	"\rthrottle_keys\x18\x03 \x03(\tR\fthrottleKeys\x12#\n" +
	"\rattempt_count\x18\x04 \x01(\rR\fattemptCount\x12\x19\n" +
	"\bqueue_id\x18\x05 \x01(\tR\aqueueId\"\x89\x01\n" +
	"\x11MessageTimestamps\x12;\n" +
	"\venqueued_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x127\n" +
	"\tleased_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bleasedAtB\"Z github.com/faisca/fila-go/filav1b\x06proto3"

var (
	file_fila_v1_messages_proto_rawDescOnce sync.Once
	file_fila_v1_messages_proto_rawDescData []byte
)

func file_fila_v1_messages_proto_rawDescGZIP() []byte {
	file_fila_v1_messages_proto_rawDescOnce.Do(func() {
		file_fila_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fila_v1_messages_proto_rawDesc), len(file_fila_v1_messages_proto_rawDesc)))
	})
	return file_fila_v1_messages_proto_rawDescData
}

var file_fila_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fila_v1_messages_proto_goTypes = []any{
	(*Message)(nil),               // 0: fila.v1.Message
	(*MessageMetadata)(nil),       // 1: fila.v1.MessageMetadata
	(*MessageTimestamps)(nil),     // 2: fila.v1.MessageTimestamps
	nil,                           // 3: fila.v1.Message.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_fila_v1_messages_proto_depIdxs = []int32{
	3, // 0: fila.v1.Message.headers:type_name -> fila.v1.Message.HeadersEntry
	1, // 1: fila.v1.Message.metadata:type_name -> fila.v1.MessageMetadata
	2, // 2: fila.v1.Message.timestamps:type_name -> fila.v1.MessageTimestamps
	4, // 3: fila.v1.MessageTimestamps.enqueued_at:type_name -> google.protobuf.Timestamp
	4, // 4: fila.v1.MessageTimestamps.leased_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fila_v1_messages_proto_init() }
func file_fila_v1_messages_proto_init() {
	if File_fila_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fila_v1_messages_proto_rawDesc), len(file_fila_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fila_v1_messages_proto_goTypes,
		DependencyIndexes: file_fila_v1_messages_proto_depIdxs,
		MessageInfos:      file_fila_v1_messages_proto_msgTypes,
	}.Build()
	File_fila_v1_messages_proto = out.File
	file_fila_v1_messages_proto_goTypes = nil
	file_fila_v1_messages_proto_depIdxs = nil
}
